### ISSUE TITLE
Issues with the next version of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [gorkang/BayesianReasoning#42]
Hi

We are preparing the next version of ggplot2 and we have found some issues with BayesianReasoning. The next version will store computed params in a separate `computed_*` field in the layer to make it clear what parts of the layer is stateful. This influences two of your tests:

https://github.com/gorkang/BayesianReasoning/blob/b7dfd9602ac45ca852a806e0461326319fd46959/tests/testthat/test-PPV_heatmap.R#L117-L119

https://github.com/gorkang/BayesianReasoning/blob/b7dfd9602ac45ca852a806e0461326319fd46959/tests/testthat/test-PPV_heatmap.R#L146-L148

where you should be using `computed_geom_params` instead of `geom_params`

We plan to release on May 31st and hope you are able to provide a fix before that

**Comment by gorkang** [comment]
Thanks for letting me know @thomasp85 . Fixed on master branch. 

I guess I need to wait until May 31st to release the fixed version to CRAN...

**Comment by thomasp85** [comment]
Either that or turn these unit tests off temporarily. If you do that you can submit it to cran and then turn it back on immediately on the master branch. In the end it is up to you
